name: flutter_architecture_templates
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  retrofit: ^4.0.3
  dio: ^5.3.4
  pretty_dio_logger: ^1.3.1
  riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  device_info_plus: ^9.1.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  common_utils: ^2.1.0
  go_router: ^12.1.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_gen_runner: ^5.3.2
  go_router_builder: ^2.3.4

  json_serializable: ^6.7.1
  freezed: ^2.4.5

  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true


